### ISSUE TITLE
No doc folder

### ISSUE THREAD

**Issue by comprodigy** [GPUOpen-Effects/TressFX#4]
No doc folder in directory amd/tressfx/ like said in the description. The documentation is supposed to be here.

**Comment by RoyLab** [comment]
I think the viewer source give a good example, but readme.md says there is a document.

**Comment by jstewart-amd** [comment]
I removed mention of the nonexistent doc folder. See de6305e55f54c8ec716c17c577b09a13ef53eb9f.

I am leaving this issue open because there is supposed to be an `amd_tressfx\doc` folder, but the documentation that would go there is quite out of date and needs to be updated before pushing to GitHub. Realistically, that is not going to happen until after GDC.

**Comment by jstewart-amd** [comment]
Okay, never mind what I said in my previous comment. I quickly put together some high-level overview slides, largely taken from previous material. The `amd_tressfx\doc` folder exists now.

More detailed documentation will have to wait until after GDC, though. For real.

**Comment by RoyLab** [comment]
Thanks jstewart~
